"""
Schema field coverage test.

Every field in ArticlePlan, SectionPlan, FAQPlan, and PlannedImage must be consumed
by at least one downstream agent, or explicitly declared in ALLOWED_UNTRACKED.

This test prevents silent "dead output" — fields the planner generates and pays for
but no agent ever reads. Adding a new schema field without updating a consumer set
causes a loud failure here, forcing an explicit decision.
"""
from models.article_plan import ArticlePlan, FAQPlan, PlannedImage, SectionPlan

# ── Consumed field sets ────────────────────────────────────────────────────────
# Verified against:
#   ArticlePlan.to_generator_block()  → ArticleAgent (article body prompt)
#   article_agent.py                  → ArticleAgent (focus_keyword placeholder check)
#   image_resolver_agent.py           → ImageResolverAgent (image resolution pipeline)

CONSUMED_ARTICLE_PLAN_FIELDS = {
    "article_thesis",           # to_generator_block
    "hook_angle",               # to_generator_block
    "local_context_foundation", # to_generator_block
    "regional_specifics",       # to_generator_block
    "primary_counter_intuition",# to_generator_block
    "primary_prohibition",      # to_generator_block
    "internal_link_keyword",    # to_generator_block
    "external_authorities",     # to_generator_block
    "conclusion_angle",         # to_generator_block
    "section_plans",            # to_generator_block (iterated over sections)
    "faq_plans",                # to_generator_block (iterated over FAQs)
    "focus_keyword",            # article_agent.py — placeholder validation
    "image_plans",              # image_resolver_agent.py — image resolution
}

CONSUMED_SECTION_PLAN_FIELDS = {
    "heading",                  # to_generator_block — section H2
    "technical_reality",        # to_generator_block
    "professional_insight",     # to_generator_block
    "local_factors",            # to_generator_block
    "safety_considerations",    # to_generator_block
    "diagnostic_tests",         # to_generator_block
    "decision_criteria",        # to_generator_block
    "realistic_limitations",    # to_generator_block
    "preventive_advice",        # to_generator_block
    "counter_intuitive_facts",  # to_generator_block
    "why_not_examples",         # to_generator_block
    "specific_numbers",         # to_generator_block
    "eeat_opportunities",       # to_generator_block
    "section_hook",             # to_generator_block
    "section_closer",           # to_generator_block
    "keyword_placement",        # to_generator_block
}

CONSUMED_FAQ_PLAN_FIELDS = {
    "question",                 # to_generator_block
    "answer_core",              # to_generator_block
    "local_angle",              # to_generator_block
}

CONSUMED_PLANNED_IMAGE_FIELDS = {
    "image_id",                 # image_resolver_agent.py
    "purpose",                  # image_resolver_agent.py
    "section_anchor",           # image_resolver_agent.py
    "why",                      # image_resolver_agent.py
    "subject",                  # image_resolver_agent.py
    "image_type",               # image_resolver_agent.py
    "generation_prompt",        # image_resolver_agent.py
    "alt_text",                 # image_resolver_agent.py
    "caption",                  # image_resolver_agent.py
    "mandatory",                # image_resolver_agent.py
}

# Fields allowed to exist without a current consumer.
# Each key is a model label; each value is a set of field names with a justification.
# An empty dict means zero untracked fields are tolerated.
ALLOWED_UNTRACKED: dict[str, set[str]] = {}


# ── Test helpers ──────────────────────────────────────────────────────────────

def _assert_coverage(model_cls, consumed: set[str], label: str) -> None:
    all_fields = set(model_cls.model_fields.keys())
    allowed = ALLOWED_UNTRACKED.get(label, set())
    covered = consumed | allowed

    untracked = all_fields - covered
    assert not untracked, (
        f"\n{label} has fields generated by the planner but never read by any agent:\n"
        + "".join(f"  - {f}\n" for f in sorted(untracked))
        + f"Add them to CONSUMED_{label.upper()}_FIELDS if a consumer exists, "
        f"or to ALLOWED_UNTRACKED['{label}'] with a justification comment."
    )

    phantom = consumed - all_fields
    assert not phantom, (
        f"\n{label} CONSUMED set references fields that no longer exist in the model:\n"
        + "".join(f"  - {f}\n" for f in sorted(phantom))
        + "Update the CONSUMED set to match the current model definition."
    )


# ── Tests ─────────────────────────────────────────────────────────────────────

def test_article_plan_field_coverage():
    _assert_coverage(ArticlePlan, CONSUMED_ARTICLE_PLAN_FIELDS, "ArticlePlan")


def test_section_plan_field_coverage():
    _assert_coverage(SectionPlan, CONSUMED_SECTION_PLAN_FIELDS, "SectionPlan")


def test_faq_plan_field_coverage():
    _assert_coverage(FAQPlan, CONSUMED_FAQ_PLAN_FIELDS, "FAQPlan")


def test_planned_image_field_coverage():
    _assert_coverage(PlannedImage, CONSUMED_PLANNED_IMAGE_FIELDS, "PlannedImage")
